### ISSUE TITLE
figureSkating 문제 예시 아웃풋 오류

### ISSUE THREAD

**Issue by doobee98** [pkiop/JS-Array-Challenge#36]
https://github.com/pkiop/JS-Array-Challenge/tree/master/Problems/figureSkating

아사다마오 양의 점수가 999점이 아닌 939점이 되어야 하는 것 같습니다.
4개 이상일 경우 큰 값 3개만 고려되어야 하는데, 그 부분이 반영되지 않은 채 example output이 나온 것으로 추정됩니다.

**Comment by pkiop** [comment]
앗 맞는 것 같습니다 ㅠㅠ 제가 만들어 놓고 고려 안하고 짠 결과를 첨부했군요
괜찮으시면 수정해주셔도 좋을 것 같아요!
