### ISSUE TITLE
Jest 등 테스트 툴 + 깃헙 액션으로 자동채점 만들기

### ISSUE THREAD

**Issue by pkiop** [pkiop/JS-Array-Challenge#64]
문제 파일 구조 변경
- solve.js 에 결과 array를 export하기
- solve.test.js 만들기

**Comment by h-sick** [comment]
네 한번 해보겠습니다!

**Comment by dongjay00** [comment]
더이상 solve.js에 console.log를 찍지 않게 만들어 보란 뜻일까요?

**Comment by pkiop** [comment]
샘플로 만들었습니다! 아직 테스트 케이스 작성 안된 문제들 도와주시면 감사할 것 같아요!
